import {
  LayoutDashboard,
  Users,
  BarChart2,
  User,
  Image,
  ChevronRight,
  ChevronDown,
  CreditCard,
  LogOut,
  UserCircle,
  Bell,
  Settings,
  Activity,
  FileChartColumnIncreasing,
  Layers2,
  Settings2,
  UserPen,
  UserCog,
  ShieldUser,
  UserStar,
  SquareUser,

  Briefcase,
} from 'lucide-react';

export const Icons: Record<string, React.ElementType> = {
  Home: LayoutDashboard, // Backwards compatibility if needed, though replaced in nav items
  LayoutDashboard,
  Users,
  BarChart2,
  FileChartColumnIncreasing,
  User,
  logo: Image,
  ChevronRight,
  ChevronsDown: ChevronDown,
  CreditCard,
  Logout: LogOut,
  UserCircle,
  Bell,
  Settings,
  Activity,
  Layers2,
  Settings2,
  UserPen,
  UserCog,
  ShieldUser,
  UserStar,
  SquareUser,
  Briefcase,
};
