steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - -t
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$SHORT_SHA
      - python-service

  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$SHORT_SHA

  - name: gcr.io/google.com/cloudsdktool/cloud-sdk
    entrypoint: gcloud
    args:
      - run
      - deploy
      - ${_SERVICE}
      - --image=${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$SHORT_SHA
      - --region=${_REGION}
      - --platform=managed
      - --service-account=${_RUNTIME_SERVICE_ACCOUNT}
      - --allow-unauthenticated
      - --memory=2Gi
      - --cpu=1
      - --concurrency=1
      - --min-instances=0
      - --max-instances=1
      - --timeout=60
      - --set-secrets=FACE_API_TOKEN=payfix-face-api-token:latest

substitutions:
  _REGION: asia-south1
  _REPOSITORY: payfix-containers
  _SERVICE: payfix-face-service
  _RUNTIME_SERVICE_ACCOUNT: payfix-face-runtime@payfix-develop.iam.gserviceaccount.com

images:
  - ${_REGION}-docker.pkg.dev/$PROJECT_ID/${_REPOSITORY}/${_SERVICE}:$SHORT_SHA

timeout: 1800s
options:
  logging: CLOUD_LOGGING_ONLY